### ISSUE TITLE
Courses should probably be listed with their links in the README.md file

### ISSUE THREAD

**Issue by sgbaird** [schwallergroup/ai4chem_course#1]
Took me a bit to realize there was something under the .qmd file (I looked at the commit history https://github.com/schwallergroup/ai4chem_course/commit/6e4ea6c7094c10446c4e737c9620a632398fbb8f)

**Comment by pschwllr** [comment]
Hi @sgbaird, this is a work in progress for a course I will teach this semester. I've added a readme and I'm closing this issue.
